apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Norboten
    type: grafana-postgresql-datasource
    uid: norboten-postgres
    url: postgres:5432
    user: norboten
    jsonData:
      database: norboten
      sslmode: disable
      postgresVersion: 1700
    secureJsonData:
      password: $POSTGRES_PASSWORD
