"""Screenshots of the real TUI, as SVG, for the site.

    uv run python site/capture.py [--out site/static/captures] [--only tui-play]

Textual can render a running app to SVG, which is the honest way to show a terminal interface on a
web page: it is the actual widget tree at the actual size, not a photograph of a terminal and not a
mock-up drawn in a design tool. The files are text, they scale, and they stay readable on a phone.

The app is driven headlessly through `run_test`, so this needs no terminal and no VM. What it shows
comes from three places, and the site says so where it matters:

* the repository itself — labs, briefings, question banks, journals, the shipped recordings;
* an in-process API loaded with the sample population (`make seed`), for Ratings and You — the
  profile captured is one of the generated sample accounts, never a real person;
* a throwaway `NORBOTEN_HOME` holding two sample lab sessions and some theory progress, so Home and
  the sessions panel have something to show. No VM exists behind them.

Doctor runs for real, on whatever machine renders the captures.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
SIZE = (150, 44)
#: A capture whose terminal is a different shape from the rest. Everything else is SIZE, which is
#: what the checks table needs to show its columns whole.
#: tui-check is shown small on Features, so it is captured narrow (bigger letters) but wide
#: enough for the checks table's four columns, and short enough not to leave dead space.
SIZES: dict[str, tuple[int, int]] = {"tui-check": (128, 26)}

#: The sample account the You capture signs in as. It is generated by seed/generate.py.
SAMPLE_USER = "seed-007"

#: Each capture: a file name, whether it is signed in as the sample user, and the steps from the
#: moment the app opens — a key name, or a number of seconds to let the screen settle.
SHOTS: tuple[tuple[str, bool, tuple[str | float, ...]], ...] = (
    ("tui-home", False, (2.0,)),
    ("tui-labs", False, ("2", 0.3, "down", "down", "down", 0.6)),
    ("tui-lab", False, ("2", 0.3, "down", "down", "down", "enter", 0.8)),
    ("tui-check", False, ("2", 0.3, "down", "down", "down", "enter", 0.8, "tab:checks", 0.4)),
    ("tui-theory", False, ("3", 0.3, "down", "down", 0.4)),
    ("tui-quiz", False, ("3", 0.3, "enter", 0.4, "1", "enter", 0.4)),
    ("tui-journals", False, ("4", 0.3, "down", "down", "down", "down", 1.2)),
    ("tui-play", False, ("5", 0.5, "down", "down", "down", "enter", 0.3, "right", "right", 0.5)),
    ("tui-ratings", False, ("6", 1.0)),
    ("tui-you", True, ("7", 1.2)),
    ("tui-system", False, ("8", 0.8)),
    ("tui-help", False, ("question_mark", 0.4)),
)


def sample_home(home: Path) -> None:
    """Two lab sessions and some theory progress, so Home is not an empty first run."""
    now = time.time()
    sessions = home / "sessions"
    sessions.mkdir(parents=True, exist_ok=True)
    samples = (
        ("hello", "alpine", "passed", now - 86400 * 2, 100),
        ("rhcsa-03-storage-and-lvm", "rocky-10", "working", now - 520, 83),
    )
    for lab_id, image, state, started, score in samples:
        body = {
            "lab_id": lab_id,
            "lab_version": "1.0.0",
            "image": image,
            "instance": "nb-sample",
            "state": state,
            "started_at": started,
            "updated_at": started + 900,
            "hint_levels": {} if state == "passed" else {"02_app_volume_has_headroom": 2},
            "attempts": [{"at": started + 900, "score_percent": score, "passed": score == 100}],
            "learner": "learner",
            "clock_started_at": started + 30,
            "rated": False,  # both labs are unrated
        }
        (sessions / f"{lab_id}.json").write_text(json.dumps(body, indent=2))
    # the last graded check of the rhcsa-03 sample session: four of five, the held file still held
    ok = ("01_boots_clean", "02_app_volume_has_headroom", "03_swap_active_after_reboot",
          "04_fstab_uses_uuid")  # fmt: skip
    held = "A process holds a deleted file on /var/lib/app."
    passes = [
        {
            "phase": phase,
            "results": [{"id": c, "passed": True, "message": "ok"} for c in ok]
            + [{"id": "05_held_space_released", "passed": False, "message": held}],
        }
        for phase in ("pre_reboot", "post_reboot")
    ]
    report = {
        "lab_id": "rhcsa-03-storage-and-lvm",
        "lab_version": "1.0.0",
        "base_image": "rocky-10",
        "passes": passes,
        "score_percent": 83,
        "passed": False,
    }
    (sessions / "rhcsa-03-storage-and-lvm.last.json").write_text(json.dumps(report, indent=2))
    theory = {
        "bash": {"answered": 12, "correct": 10, "best_streak": 6},
        "linux": {"answered": 12, "correct": 8, "best_streak": 4},
        "networking": {"answered": 7, "correct": 4, "best_streak": 3},
    }
    (home / "progress.json").write_text(json.dumps({"theory": theory}, indent=2))
    from norboten import settings

    settings.save(setup_done=True)  # past the first run: the setup screen would cover every shot


def sample_api():
    """The real API in this process, with the sample population loaded, as an httpx client."""
    from fastapi.testclient import TestClient

    from norboten_api import seed
    from norboten_api.main import create_app

    for name in ("httpx", "httpx2"):
        logging.getLogger(name).setLevel(logging.WARNING)
    app = create_app()
    client = TestClient(app, base_url="http://api.sample")
    client.__enter__()  # runs the lifespan: the stores exist from here on
    client.portal.call(seed.load, app.state.accounts)
    return client


async def capture(out: Path, only: set[str]) -> list[Path]:
    from norboten.tui import data
    from norboten.tui.app import NorbotenApp

    api = sample_api()
    data.use(api)
    written: list[Path] = []
    out.mkdir(parents=True, exist_ok=True)
    try:
        for name, signed_in, steps in SHOTS:
            if only and name not in only:
                continue
            if signed_in:
                os.environ["NORBOTEN_DEBUG_USER"] = SAMPLE_USER
            else:
                os.environ.pop("NORBOTEN_DEBUG_USER", None)
            app = NorbotenApp()
            async with app.run_test(size=SIZES.get(name, SIZE)) as pilot:
                await pilot.pause(0.8)  # doctor and the account panel answer
                for step in steps:
                    if isinstance(step, float):
                        await pilot.pause(step)
                    elif step.startswith("tab:"):  # a lab screen's tab, by id
                        app.screen.query_one("TabbedContent").active = step[4:]
                    else:
                        await pilot.press(step)
                await pilot.pause()
                target = out / f"{name}.svg"
                app.save_screenshot(str(target))
                written.append(target)
    finally:
        data.use(None)
        api.__exit__(None, None, None)
    return written


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=SITE / "static" / "captures")
    ap.add_argument(
        "--only", action="append", default=[], help="capture just this one (repeatable)"
    )
    args = ap.parse_args()
    # A short home: doctor checks the UNIX socket path length under it.
    home = Path(tempfile.mkdtemp(prefix="nbcap-", dir="/tmp"))
    os.environ["NORBOTEN_HOME"] = str(home)
    os.environ["NORBOTEN_API"] = "http://api.sample"
    sample_home(home)
    try:
        written = asyncio.run(capture(args.out, set(args.only)))
    except Exception as e:  # a broken capture is a message, not a traceback
        print(f"capture failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 1
    for path in written:
        shown = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
        print(f"{shown}  {path.stat().st_size // 1024} KiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
