import os
import tempfile

SCRIPT = "/usr/local/bin/top-talkers"
LOG = """# generated by the edge proxy
10.1.1.1 - - [x] "GET / HTTP/1.1" 200 1

10.1.1.1 - - [x] "GET / HTTP/1.1" 200 1
#10.9.9.9 - - [x] "GET / HTTP/1.1" 200 1
# 10.9.9.9 commented too
10.2.2.2 - - [x] "GET / HTTP/1.1" 200 1

"""


def check(ctx):
    if not os.access(SCRIPT, os.X_OK):
        return ctx.failed(f"{SCRIPT} does not exist or is not executable.")
    with tempfile.NamedTemporaryFile("w", prefix=".norboten-probe-", delete=False) as f:
        f.write(LOG)
    try:
        r = ctx.run([SCRIPT, f.name])
    finally:
        os.unlink(f.name)
    want = ["2 10.1.1.1", "1 10.2.2.2"]
    if r.code != 0 or r.out.strip().splitlines() != want:
        return ctx.failed(
            "Comment or blank lines are counted as clients.",
            "expected:\n" + "\n".join(want) + "\n\ngot:\n" + r.text,
        )
    return ctx.passed("Comments and blank lines are ignored.")
