"""docs/api-reference.md, written from the application itself.

    python -m norboten_api.reference > docs/api-reference.md

Every route, its parameters, its body and whether it needs a token come from the OpenAPI document
FastAPI builds, and each description is the endpoint's own docstring — so the reference cannot
drift from the code. CI regenerates it and fails when the committed copy differs.
"""

from __future__ import annotations

import sys

GROUPS = {
    "meta": "Health and metrics",
    "auth": "Accounts and signing in",
    "labs": "The lab catalogue",
    "quiz": "Theory",
    "rated": "Rated labs and rated theory",
    "progress": "Anonymous progress",
    "profile": "Profiles, attempts and the board",
    "play": "Live and recorded sessions",
    "chat": "The consultant",
    "donations": "Donations",
    "telemetry": "Telemetry",
    "oauth": "OAuth for MCP clients",
}

HEADER = """# API reference

<!-- generated by `python -m norboten_api.reference`; do not edit by hand -->

The API is served at `https://api.<domain>` (`http://localhost:8000` with `make stack-up`).
Requests and responses are JSON unless noted. The interactive form of the same document is at
`/docs` on any running API.

**Signing requests.** Endpoints marked *token* need `Authorization: Bearer <token>` — a `web` or
`cli` token from signing in with GitHub (`/auth/github/poll` in a terminal,
`/auth/github/exchange` on the site), which is the only way in: no password anywhere. On a server
with `NORBOTEN_REQUIRE_AUTH=false` (tests, `make stack-up`) `X-Debug-User: <id>` stands in for
one. Endpoints marked *public* need nothing.

**Errors** are `{"detail": "…"}` with a status: 401 no or bad token, 403 not yours (or denied on
GitHub), 404 unknown, 409 conflict (a taken nick), 410 gone (a sign-in expired or already used),
422 invalid body, 428 still waiting for GitHub, 429 rate-limited, 502/503 a model provider, GitHub
or Discord failed, or this deployment has none.
"""


def _schema_name(ref: dict | None) -> str:
    if not ref:
        return ""
    if "$ref" in ref:
        return ref["$ref"].rsplit("/", 1)[-1]
    if ref.get("type") == "array":
        return f"list of {_schema_name(ref.get('items'))}"
    return ref.get("type", "")


def _fields(spec: dict, name: str) -> list[str]:
    schema = spec.get("components", {}).get("schemas", {}).get(name, {})
    required = set(schema.get("required", []))
    out = []
    for field, prop in schema.get("properties", {}).items():
        kind = _schema_name(prop) or " or ".join(
            _schema_name(p) for p in prop.get("anyOf", []) if p.get("type") != "null"
        )
        bits = [f"`{field}`", kind or "any"]
        if field not in required:
            bits.append("optional")
        for key, label in (
            ("minLength", "min"),
            ("maxLength", "max"),
            ("minimum", "≥"),
            ("maximum", "≤"),
        ):
            if key in prop:
                bits.append(f"{label} {prop[key]}")
        out.append(" · ".join(bits))
    return out


def render() -> str:
    from norboten_api.main import create_app

    spec = create_app().openapi()
    by_group: dict[str, list[str]] = {}
    for path, methods in spec["paths"].items():
        for method, op in methods.items():
            tag = (op.get("tags") or ["meta"])[0]
            params = op.get("parameters", [])
            needs_token = any(p["name"] == "authorization" for p in params)
            visible = [p for p in params if p["name"] not in ("authorization", "x-debug-user")]
            lines = [f"### `{method.upper()} {path}`", ""]
            lines.append("*token*" if needs_token else "*public*")
            lines.append("")
            doc = (op.get("description") or op.get("summary") or "").strip()
            if doc:
                lines += [" ".join(doc.split()), ""]
            if visible:
                lines.append("| Parameter | In | Type | Required |")
                lines.append("|---|---|---|---|")
                for p in visible:
                    kind = _schema_name(p.get("schema")) or " or ".join(
                        _schema_name(s)
                        for s in p.get("schema", {}).get("anyOf", [])
                        if s.get("type") != "null"
                    )
                    required = "yes" if p.get("required") else "no"
                    lines.append(f"| `{p['name']}` | {p['in']} | {kind} | {required} |")
                lines.append("")
            body = (
                op.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if body:
                name = _schema_name(body)
                lines.append(f"Body — `{name}`:")
                lines.append("")
                lines += [f"- {f}" for f in _fields(spec, name)]
                lines.append("")
            by_group.setdefault(tag, []).append("\n".join(lines))
    out = [HEADER]
    for tag, title in GROUPS.items():
        if tag in by_group:
            out.append(f"## {title}\n")
            out += by_group.pop(tag)
    for tag, entries in by_group.items():
        out.append(f"## {tag}\n")
        out += entries
    return "\n".join(out).rstrip() + "\n"


if __name__ == "__main__":
    sys.stdout.write(render())
